name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

env:
  FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
  ALGOLIA_APP_ID: 70J79DW1HQ
  ALGOLIA_ADMIN_KEY: ${{secrets.ALGOLIA_ADMIN_KEY}}
  ALGOLIA_INDEX_NAME: content
  ALGOLIA_INDEX_FILE: public/algolia.json
  HUGO_SALT: ${{secrets.HUGO_SALT}}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          extended: true
      - run: npm ci
      - run: npm run build
      #      - run: npm run deploy
      - run: echo "Build completed successfully."
      - run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_WEB_PROJECTS_2C5B2 }}'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_WEB_PROJECTS_2C5B2 }}'
          channelId: default
          projectId: my-web-projects-2c5b2
